# Generated by Django 4.2.11 on 2024-05-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0006_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
